language: c
compiler:
    - gcc
    - clang

sudo: false

branches:
    only:
        - master
        - test

addons:
    apt:
        packages:
        - ninja-build
        - liblua5.2-dev

script:
    - python ./bootstrap.py --ci --cxx=$CC
    - ninja
    - ./test/bin/btest
